// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ordfiltInC
NumericMatrix ordfiltInC(NumericMatrix data, double x, NumericMatrix weightedMatrix);
RcppExport SEXP oXim_ordfiltInC(SEXP dataSEXP, SEXP xSEXP, SEXP weightedMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type weightedMatrix(weightedMatrixSEXP);
    __result = Rcpp::wrap(ordfiltInC(data, x, weightedMatrix));
    return __result;
END_RCPP
}
